menu:
    Blog: /
    Archive: /archives/
    #Weibo: xxx
    GitHub: https://github.com/y-not-u
    Mail: mailto:voganwong@hotmail.com
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png
author: Vogan

# Comment
disqus: vatery
# duoshuo:

# Analytics
ca: l6ok4h42je

# Copyright Infomation
startyear: 2016
